version: '2'
services:
    # Web server container
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./client/build:/var/www/immoscout24
        links:
            - nodejs
        ports:
            - "80:80"
        depends_on:
            - nodejs
        restart: unless-stopped
    
    # Application container
    nodejs:
        build:
            context: ./
            dockerfile: ./docker/nodejs/Dockerfile
        environment:
            - PORT=3000
        volumes:
            - ./app/:/app/
            - node_modules:/app/node_modules
        restart: unless-stopped

volumes:
    node_modules:
